package main

import (
	"context"
	"fmt"
	"os"
	"sort"
	"strings"
	"telephony/internal/config"
	"telephony/internal/shared/database/postgres"
	"telephony/pkg/logger"
	"time"
)

type dictionary struct {
	MainType    string
	Name        string
	Value       string
	Description string
}

func main() {
	var ctx, cancel = context.WithTimeout(context.Background(), time.Second*10)
	defer cancel()

	log, err := logger.NewLogger()
	if err != nil {
		panic(err)
	}
	defer log.Sync()

	cfg := config.MustConfig(log)

	pool, err := postgres.New(ctx, cfg.Postgres, log)
	if err != nil {
		log.Errorf("failed to connect to postgres: %v", err)
		return
	}
	defer pool.Close()

	transaction := postgres.NewTransactionsRepos(cfg.Postgres, pool)

	tx, err := transaction.BeginTransaction(ctx)
	if err != nil {
		log.Errorf("failed to begin transaction: %v", err)
		return
	}
	defer transaction.Rollback(ctx, tx)

	rows, err := tx.Query(ctx, `SELECT main_type, key, value, comment FROM dictionary`)
	if err != nil {
		log.Errorf("failed to query dictionary values: %v", err)
		return
	}
	defer rows.Close()

	var dictionaryValues []*dictionary

	for rows.Next() {
		var dictionaryValue dictionary

		err = rows.Scan(&dictionaryValue.MainType, &dictionaryValue.Name, &dictionaryValue.Value, &dictionaryValue.Description)
		if err != nil {
			log.Errorf("failed to scan dictionary values: %v", err)
			return
		}
		dictionaryValues = append(dictionaryValues, &dictionaryValue)
	}

	// Группируем по MainType
	grouped := make(map[string][]*dictionary)
	for _, d := range dictionaryValues {
		grouped[d.MainType] = append(grouped[d.MainType], d)
	}

	// Путь к файлу констант
	const filePath = "./internal/domain/dictionary_consts.go"

	// Удаляем старый файл, если есть
	if err := os.Remove(filePath); err != nil && !os.IsNotExist(err) {
		log.Errorf("failed to remove old dictionary_consts.go file: %v", err)
		return
	}

	// Создаём новый файл
	f, err := os.Create(filePath)
	if err != nil {
		log.Errorf("failed to create dictionary_consts.go: %v", err)
		return
	}
	defer f.Close()

	// Шапка файла
	header := `// Code generated by dictionary generator script; DO NOT EDIT.

package domain

`
	if _, err := f.WriteString(header); err != nil {
		log.Errorf("failed to write header: %v", err)
		return
	}

	// Для детерминированного вывода сортируем типы по алфавиту
	var keys []string
	for k := range grouped {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, mainType := range keys {
		// Пишем тип
		typeDef := fmt.Sprintf("type %s string\n\n", mainType)
		if _, err := f.WriteString(typeDef); err != nil {
			log.Errorf("failed to write type definition: %v", err)
			return
		}

		// Пишем константы
		if _, err := f.WriteString("const (\n"); err != nil {
			log.Errorf("failed to write const block start: %v", err)
			return
		}

		for _, d := range grouped[mainType] {
			comment := strings.ReplaceAll(d.Description, "\n", "\n\t// ")
			constLine := fmt.Sprintf("\t// %s\n\t// Значение: %q\n\t%s %s = %q\n\n",
				d.Name, d.Value, d.Name, mainType, d.Value)
			if _, err := f.WriteString("// " + comment + "\n"); err != nil {
				log.Errorf("failed to write comment: %v", err)
				return
			}
			if _, err := f.WriteString(constLine); err != nil {
				log.Errorf("failed to write const: %v", err)
				return
			}
		}

		if _, err := f.WriteString(")\n\n"); err != nil {
			log.Errorf("failed to write const block end: %v", err)
			return
		}
	}

	log.Infof("dictionary_consts.go successfully generated with %d constants", len(dictionaryValues))
}
